copyright: Copyright &copy;2022, IO-Aero.

edit_uri: ""

extra:
  generator: false
extra_css:
  - assets/pymdownx-extras/extra-b1466b3f51.css
extra_javascript:
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/pymdownx-extras/extra-loader-9e2c67b9.js

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.tilde
  - toc : {
    toc_depth: "1-3"
  }

nav:
  - Home: index.md
  - Library:
      - Requirements: library_requirements.md
      - Installaion: library_installation.md
      - Configuration: library_configuration.md
      - API Documentation: library_api_documentation.md
  - Release Documents:
    - Release Notes: release_notes.md
    - Release History: release_history.md
    - Release Schedule: release_schedule.md
  - License: LICENSE.md

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 3
            paths: [src/io_template]
            show_root_heading: false
            show_source: true
  - search

repo_name: GitHub
repo_url: https://github.com/io-aero/io-template

site_name: IO-TEMPLATE - Template Library
site_url: https://io-aero.com/
site_description: Template Library
site_author: IO-Aero Team

theme:
  favicon: img/IO-Aero Logo.png
  features:
    - search.highlight
    - search.suggest
  language: en
  logo: img/IO-Aero Logo.png
  name: material
  palette:
    primary: blue
    accent: red

use_directory_urls: false
